DEVICE_NAME = JCA-123

SW_VERSION_MAJOR ?= 0
SW_VERSION_MINOR ?= 5
SW_VERSION_PATCH ?= 0

SW_VERSION_NAME = $(SW_VERSION_MAJOR).$(SW_VERSION_MINOR).$(SW_VERSION_PATCH)

VERSION_DEFS = \
-DSW_VERSION_MAJOR=$(SW_VERSION_MAJOR) \
-DSW_VERSION_MINOR=$(SW_VERSION_MINOR) \
-DSW_VERSION_PATCH=$(SW_VERSION_PATCH) \
-DSW_VERSION_NAME=$(SW_VERSION_NAME) \
